<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Greenhouse.Core\Greenhouse.Core.csproj" />
    <ProjectReference Include="..\Greenhouse.Mqtt\Greenhouse.Mqtt.csproj" />
    <ProjectReference Include="..\Greenhouse.Storage\Greenhouse.Storage.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
